### ISSUE TITLE
Write README.md

### ISSUE THREAD

**Issue by wangqing1218** [ACLoong/nba-tall#1]
We should write the **README.md** file here.

This issue we will do 2 things:
1. Write the **README_ZH.md** file in Chinese.
2. Translate **README_ZH.md** to an English one which named **README.md**.

I think you @MrKingHH can write the Chinese version, then create an issue for others to translate the English version.

This is the outline for you to reference.
1. Background
2. Introduction
3. Structure
4. Details of Sub-System
5. How to Contibute
6. Thanks
etc.

**Comment by wangqing1218** [comment]
I think you @MrKingHH do the step1(write the Chinese version), and you @Tina66 translate it into English one.

**Comment by wangqing1218** [comment]
By the way, you should introduce this repository in detail because we should make the other followers understand it.

**Comment by Tina66** [comment]
got it.I will do this after Mr.Jin.

**Comment by MrKingHH** [comment]
ok,i have finished it.

**Comment by MrKingHH** [comment]
**This issue was finished.**
