### ISSUE TITLE
Translate README_ZH.md to an English

### ISSUE THREAD

**Issue by MrKingHH** [ACLoong/nba-tall#5]
The Chinese edition of README_ZH.md have been finished on the Github. Now you should translate it into an English edition which named README.md.

From this work , you can master some skills as follows :

1. Improve your English writing skills
2. Learn the basic grammar of Markdown
3. Be familiar with the general process of your future job.

Come on ! Have a try @Tina66

**Comment by Tina66** [comment]
got it!

**Comment by Tina66** [comment]
The latest commit is the final one. I cannot cut other two commits when I create a new pr...

**Comment by MrKingHH** [comment]
**This issue was finished.**
